---
- include_vars: advanced_tools.yml

- name: install dependencies for git
  yum: name={{ item }} state=installed
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - perl-ExtUtils-MakeMaker

- name: check if git {{ git_version }} is already installed
  shell: /usr/local/bin/git --version
  register: git_version_result
  ignore_errors: true

- name: download and extract git tarball
  unarchive: copy=no src=https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz dest=/var/ansible
  when: (git_version_result.rc != 0) or (git_version_result.stdout != 'git version {{ git_version }}')

- name: make git
  command: make prefix=/usr/local all chdir=/var/ansible/git-{{ git_version }}
  when: (git_version_result.rc != 0) or (git_version_result.stdout != 'git version {{ git_version }}')

- name: make install git
  command: make install prefix=/usr/local chdir=/var/ansible/git-{{ git_version }}
  when: (git_version_result.rc != 0) or (git_version_result.stdout != 'git version {{ git_version }}')
